<a href="https://colab.research.google.com/github/Riteshvaswal/spam-filter-detection/blob/main/fakenewsiit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import numpy as np


In [40]:
df=pd.read_csv(r'/content/sample_data/train (1).csv')
df.shape

(396947, 3)

In [41]:
df=df.dropna()
df.shape

(396946, 3)

In [42]:
df1=df.copy()
df2=df.copy()


In [43]:
df1.shape,df2.shape

((396946, 3), (396946, 3))

In [44]:
df1=df1[df1['target']==0.0]
df1.shape

(372328, 3)

In [45]:
df2=df2[df2['target']==1.0]
df2.shape

(24618, 3)

In [46]:
df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [47]:

df.shape

(396946, 3)

In [48]:
df1=df1.iloc[:100000,:]
df1.shape

(100000, 3)

In [49]:
df=pd.concat([df1,df2])
df.shape

(124618, 3)

In [50]:
# df=df.iloc[:1000,:]
# df.shape

In [51]:
df.reset_index(drop=True,inplace=True)
df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [52]:
df[df['target']==1.0].index

Int64Index([100000, 100001, 100002, 100003, 100004, 100005, 100006, 100007,
            100008, 100009,
            ...
            124608, 124609, 124610, 124611, 124612, 124613, 124614, 124615,
            124616, 124617],
           dtype='int64', length=24618)

In [53]:
df = df.sample(frac = 1)

In [54]:
df[df['target']==1.0].index

Int64Index([116393, 110085, 113024, 107352, 101825, 113347, 105523, 123064,
            116149, 108640,
            ...
            111546, 115482, 110062, 123812, 122245, 120048, 123058, 119976,
            121283, 106679],
           dtype='int64', length=24618)

In [55]:
df.shape

(124618, 3)

In [56]:
# df=df.iloc[:100000,:]
df['target'].dtypes

dtype('float64')

In [57]:
X=df.drop(['qid'],axis=1)
X.head()

question_text  target
116393  Is it fine to be friends with guys? I am a gir...     1.0
36336   Why are redlining practices in real estate all...     0.0
69608   Which college should I choose between BITS and...     0.0
52362   Our stomach has a capability of digesting the ...     0.0
22641   I am designing a concept museum on business hi...     0.0

In [58]:
df['target'].value_counts()

0.0    100000
1.0     24618
Name: target, dtype: int64

In [59]:
Y=df['target']
Y.head()

116393    1.0
36336     0.0
69608     0.0
52362     0.0
22641     0.0
Name: target, dtype: float64

In [60]:
X.shape,Y.shape

((124618, 2), (124618,))

In [61]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [62]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [63]:
voc_size=10000

In [64]:
messages=X.copy()

In [65]:
messages.head()

question_text  target
116393  Is it fine to be friends with guys? I am a gir...     1.0
36336   Why are redlining practices in real estate all...     0.0
69608   Which college should I choose between BITS and...     0.0
52362   Our stomach has a capability of digesting the ...     0.0
22641   I am designing a concept museum on business hi...     0.0

In [66]:
messages['question_text'][1]

'Do you have an adopted dog, how would you encourage people to adopt and not shop?'

In [67]:
l1=[]
count=0

for i in messages['question_text']:
  count+=1
  print(count)
  print(i)
  print(len(i),i)
  l1.append(len(i))
max(l1)

Streaming output truncated to the last 5000 lines.
Can we design trapezoidal combined footing in any of the structural design software?
84 Can we design trapezoidal combined footing in any of the structural design software?
43929
How do I set Ethernet connection as metered in Windows 10?
58 How do I set Ethernet connection as metered in Windows 10?
43930
Do you think MS Dhoni will select Harbhajan Singh in playing 11 for his team CSK?
81 Do you think MS Dhoni will select Harbhajan Singh in playing 11 for his team CSK?
43931
What should a wise person do by age 20, 30, 40, 50, 60?
55 What should a wise person do by age 20, 30, 40, 50, 60?
43932
What do you think about Morocco launching its first observation satellite?
74 What do you think about Morocco launching its first observation satellite?
43933
Why do some people have one long?
33 Why do some people have one long?
43934
It’s 2058. What features will the 50th anniversary iPhone have?
63 It’s 2058. What features will the 50th anniver

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
When will Israel cease to exist so Palestine can take over?
59 When will Israel cease to exist so Palestine can take over?
122953
What are some health benefits of using hemp milk?
49 What are some health benefits of using hemp milk?
122954
What is a mechanical weathering?
32 What is a mechanical weathering?
122955
Are Chinese women unattractive?
31 Are Chinese women unattractive?
122956
Why do I want to have sex with my sister?
41 Why do I want to have sex with my sister?
122957
How can we improve BOD in waste water treatment plant?
54 How can we improve BOD in waste water treatment plant?
122958
What are some good hobby recommendations and why?
49 What are some good hobby recommendations and why?
122959
What do you think about Muslims who aren't associated with terrorism? Should I consider them terrorist because they belong to that religion?
140 What do you think about Muslims who aren't associated with terrorism? Should I consider th

878

In [68]:
sent_length=max(l1)
sent_length

878

In [69]:
messages.reset_index(inplace=True)

In [70]:
import nltk
import re
from nltk.corpus import stopwords

In [71]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [72]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):

    review = re.sub('[^a-zA-Z]', ' ', messages['question_text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [73]:
corpus[1]

'redlin practic real estat allow happen'

In [74]:
messages['question_text'][1]

'Why are redlining practices in real estate allowed to happen?'

In [75]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[1825,
  9086,
  6907,
  2735,
  4076,
  2994,
  4646,
  9978,
  5026,
  2980,
  4102,
  9846,
  368,
  1622,
  179,
  6907,
  4180,
  2419,
  5692,
  6928,
  4937,
  2770,
  9340],
 [7627, 4878, 5262, 9883, 1503, 9871],
 [1816, 564, 8474, 2362],
 [9692, 4, 6085, 2243, 7618, 6089, 481, 2604, 9172, 6849, 9692],
 [3835, 6951, 256, 8002, 3009, 1876, 8442, 7392, 5692, 1230, 4464, 1258],
 [4899, 6429, 9500, 922, 9995],
 [8048, 3709, 3310, 9912],
 [2472, 455, 7529, 2472, 3357, 4186, 8619, 7146],
 [4937, 3229, 9565],
 [3844, 6408, 5346],
 [1757, 1950, 7035, 7392, 3859, 6656, 5908],
 [8442, 3129, 9681, 2006, 7997, 7851, 269],
 [7383, 9396, 8054, 2312, 2057, 6408],
 [9106, 3681, 7934, 6803, 7877, 3049, 4971, 7877, 9259, 7877, 7877],
 [9213, 49, 3291, 4249, 8935, 8417, 6402],
 [2666, 2662, 4337, 5281, 9932, 1333, 4866],
 [9434, 8392, 7302],
 [2842, 9696, 2496, 455, 4141, 4839, 8376, 6868],
 [3233, 8347, 7290, 3223, 8911, 1816, 7290, 2937, 5043],
 [7753, 3357, 6466, 7480],
 [3945, 3263, 2419, 54

In [76]:
# sent_length=190
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4937 2770 9340]
 [   0    0    0 ... 9883 1503 9871]
 [   0    0    0 ...  564 8474 2362]
 ...
 [   0    0    0 ... 5443 2828 2693]
 [   0    0    0 ... 3387 5288 7489]
 [   0    0    0 ... 9761 3553 5869]]


In [77]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 878, 40)           400000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [78]:
len(embedded_docs),Y.shape

(124618, (124618,))

In [79]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [80]:
X_final

array([[   0,    0,    0, ..., 4937, 2770, 9340],
       [   0,    0,    0, ..., 9883, 1503, 9871],
       [   0,    0,    0, ...,  564, 8474, 2362],
       ...,
       [   0,    0,    0, ..., 5443, 2828, 2693],
       [   0,    0,    0, ..., 3387, 5288, 7489],
       [   0,    0,    0, ..., 9761, 3553, 5869]], dtype=int32)

In [81]:
X_final.shape,y_final.shape

((124618, 878), (124618,))

In [82]:
# X_final=b = X_final[np.logical_not(np.isnan(X_final))]


In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [84]:
X_train.shape,y_train.shape

((83494, 878), (83494,))

In [85]:
X_test.shape,y_test.shape

((41124, 878), (41124,))

In [86]:
# model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=1,batch_size=64)

In [87]:
# scores = model.evaluate(X_test, y_test, verbose=0)
# print("Accuracy: %.2f%%" % (scores[1]*100))

In [88]:
# # y_pred1=model.predict_classes(X_test)
# y_pred1= model.predict(X_test)
# y_pred1=np.round(y_pred1)
# y_pred1=y_pred1.astype('float')

In [89]:
# from sklearn.metrics import confusion_matrix

# confusion_matrix(y_test,y_pred1)

In [90]:
# from sklearn.metrics import accuracy_score
# accuracy_score(y_test,y_pred1)

In [91]:
# from sklearn.metrics import classification_report
# print(classification_report(y_test,y_pred1))

In [92]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 878, 40)           400000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 513,001
Trainable params: 513,001
Non-trainable params: 0
_________________________________________________________________
None


In [93]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=1,batch_size=64)

1305/1305 [==============================] - 3542s 3s/step - loss: 0.2990 - accuracy: 0.8742 - val_loss: 0.2592 - val_accuracy: 0.8929


In [95]:
# y_pred1=model.predict_classes(X_test)
y_pred2= model1.predict(X_test)
y_pred2=np.round(y_pred2)
y_pred2=y_pred2.astype('float')

1286/1286 [==============================] - 392s 305ms/step


In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.8928849333722401

In [97]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred2)

array([[30849,  2251],
       [ 2154,  5870]])

In [100]:
list(zip(y_pred2,y_test))

[(array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([1.]), 1.0),
 (array([0.]), 0.0),
 (array([1.]), 0.0),
 (array([0.]), 0.0),
 (array([1.]), 1.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 1.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([1.]), 0.0),
 (array([1.]), 1.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([1.]), 1.0),
 (array([0.]), 0.0),
 (array([1.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.]), 0.0),
 (array([0.])

In [102]:
df3=pd.DataFrame(data=list(zip(y_pred2,y_test)),columns=['y_pred2','y_test'])
df3.shape

(41124, 2)

In [105]:
df3.to_csv(r'\content\sample_data\df3.csv')