In [1]:
import pandas as pd
import numpy as np
import numpy


In [ ]:
df=pd.read_csv(r'/content/sample_data/train (1).csv')
df.shape

(1157872, 3)

In [ ]:
# df1=df.copy()
# df2=df.copy()


In [ ]:
# df1.shape,df2.shape

In [ ]:
# df1=df1[df1['target']==0.0]
# df1.shape

In [ ]:
# df2=df2[df2['target']==1.0]
# df2.shape

In [ ]:
df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [ ]:

df.shape

(1157872, 3)

In [ ]:
# df1=df1.iloc[:100000,:]
# df1.shape

In [ ]:
# df=pd.concat([df1,df2])
# df.shape

In [ ]:
# df=df.iloc[:1000,:]
# df.shape

In [ ]:
df.reset_index(drop=True,inplace=True)
df.head()

qid                                      question_text  \
0  00002165364db923c7e6  How did Quebec nationalists see their province...   
1  000032939017120e6e44  Do you have an adopted dog, how would you enco...   
2  0000412ca6e4628ce2cf  Why does velocity affect time? Does velocity a...   
3  000042bf85aa498cd78e  How did Otto von Guericke used the Magdeburg h...   
4  0000455dfa3e01eae3af  Can I convert montra helicon D to a mountain b...   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [ ]:
df[df['target']==1.0].index

Int64Index([     22,      30,     110,     114,     115,     119,     127,
                144,     156,     167,
            ...
            1157712, 1157731, 1157740, 1157746, 1157755, 1157775, 1157791,
            1157804, 1157833, 1157855],
           dtype='int64', length=71622)

In [ ]:
df = df.sample(frac = 1)

In [ ]:
df[df['target']==1.0].index

Int64Index([  23387, 1137038,  152330, 1099674, 1034457, 1133126,  839258,
             739288,  306485,   41452,
            ...
             286976,  589716, 1021660, 1023880, 1134387,  405172,  608744,
             651386,  562595,  737371],
           dtype='int64', length=71622)

In [ ]:
df.shape

(1157872, 3)

In [ ]:
# df=df.iloc[:100000,:]
df['target'].dtypes

dtype('float64')

In [ ]:
X=df.drop(['qid'],axis=1)
X.head()

question_text  target
935897  What are the potential health risks if Irritab...     0.0
923700  Can I submit same document in different docume...     0.0
138482                    Is math a psychopathic science?     0.0
839633             Which race of people litters the most?     0.0
627577        Siblings are more important than boyfriend?     0.0

In [ ]:
df=df.dropna()
df.shape

(1157871, 3)

In [ ]:
df['target'].value_counts()

0.0    1086249
1.0      71622
Name: target, dtype: int64

In [ ]:
Y=df['target']
Y.head()

935897    0.0
923700    0.0
138482    0.0
839633    0.0
627577    0.0
Name: target, dtype: float64

In [ ]:
X.shape,Y.shape

((1157872, 2), (1157871,))

In [ ]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
voc_size=10000

In [ ]:
messages=X.copy()

In [ ]:
messages.head()

question_text  target
935897  What are the potential health risks if Irritab...     0.0
923700  Can I submit same document in different docume...     0.0
138482                    Is math a psychopathic science?     0.0
839633             Which race of people litters the most?     0.0
627577        Siblings are more important than boyfriend?     0.0

In [ ]:
messages['question_text'][1]

'Do you have an adopted dog, how would you encourage people to adopt and not shop?'

In [ ]:
l1=[]
count=0

for i in messages['question_text']:
  count+=1
  print(count)
  print(i)
  print(len(i),i)
  l1.append(len(i))
max(l1)

Streaming output truncated to the last 5000 lines.
254208
Which is best business forstudent?
34 Which is best business forstudent?
254209
What actions can a defence personnel take against road rage? (India)?
69 What actions can a defence personnel take against road rage? (India)?
254210
I have a really small head and thin face, are there any foods I can eat that will make my face more full?
105 I have a really small head and thin face, are there any foods I can eat that will make my face more full?
254211
How are diamond reserves made?
30 How are diamond reserves made?
254212
How can I reach IIEST Shibpur from Sealdah Railway Station?
59 How can I reach IIEST Shibpur from Sealdah Railway Station?
254213
Did Adolf Hitler do anything wrong?
35 Did Adolf Hitler do anything wrong?
254214
What is the best form of civic engagement if my elected officials already agree with me on the issues?
102 What is the best form of civic engagement if my elected officials already agree with me on the iss

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
47 What do you do when you feel lost in your life?
490145
Which hotel and resorts has the best Andaman Nicobar tour package for newly-wed couples?
88 Which hotel and resorts has the best Andaman Nicobar tour package for newly-wed couples?
490146
Should mistreated minorities and other social groups defend themselves using all means available? What would you do if your society discriminated you factually?
160 Should mistreated minorities and other social groups defend themselves using all means available? What would you do if your society discriminated you factually?
490147
Do Korean guys like Chinese girls?
34 Do Korean guys like Chinese girls?
490148
What are some legal issues around selling phone numbers?
56 What are some legal issues around selling phone numbers?
490149
What was the optional subject of Miss Ruchira Kamboj (IFS)?
59 What was the optional subject of Miss Ruchira Kamboj (IFS)?
490150
Why would Littlefiger give Bran's as

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
83 Why has India been a democratic murdering tribe for the past 70 years in the world?
571320
What is the mechanism of action of sildenafil?
46 What is the mechanism of action of sildenafil?
571321
What is a snake's taxonomy?
27 What is a snake's taxonomy?
571322
I am histrionic. How do I become normal and capable of having healthy friendships/relationships?
96 I am histrionic. How do I become normal and capable of having healthy friendships/relationships?
571323
A few weeks ago I saw dreams of my bones being tangled and broken, this week I saw my nails and muscles shrinking. What does this mean?
135 A few weeks ago I saw dreams of my bones being tangled and broken, this week I saw my nails and muscles shrinking. What does this mean?
571324
What family does cheetah belongs to?
36 What family does cheetah belongs to?
571325
What are the top tourists spots in Kashmir and Himachal Pradesh?
64 What are the top tourists spots in Kashmir and

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
79 How do I learn an make a career in RPA? Is there any .net background mandatory?
763041
Is Instant booking possible of Volvo buses from Delhi to Allahabad?
67 Is Instant booking possible of Volvo buses from Delhi to Allahabad?
763042
What are the rights of an indemnifier?
38 What are the rights of an indemnifier?
763043
Why do people freak out over guys wearing panties?
50 Why do people freak out over guys wearing panties?
763044
What is the best exercise-based introduction to singular Value decomposition?
77 What is the best exercise-based introduction to singular Value decomposition?
763045
Did your first Android app made a hit in the Play Store?
56 Did your first Android app made a hit in the Play Store?
763046
Why is photogrammetry so useful in every field?
47 Why is photogrammetry so useful in every field?
763047
What prank should I play on my Ex-girlfriend?
45 What prank should I play on my Ex-girlfriend?
763048
Where did the N

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
74 How was the tiny unoccupied part of Belgium in World war One administered?
1050973
What is the point in having the ability to disable further comments on posts?
77 What is the point in having the ability to disable further comments on posts?
1050974
I am totally new to trading Ethereum. What should I know?
57 I am totally new to trading Ethereum. What should I know?
1050975
Do animals think other animals are cute like humans think some animals are cute?
80 Do animals think other animals are cute like humans think some animals are cute?
1050976
Can Saturn be very harmful for a person whose lagna and rashi is taurus?
72 Can Saturn be very harmful for a person whose lagna and rashi is taurus?
1050977
Is there any problem in giving pharmacy licence on rent in India?
65 Is there any problem in giving pharmacy licence on rent in India?
1050978
How do I get rid of a lot of continuous negative thoughts?
58 How do I get rid of a lot of conti

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



Streaming output truncated to the last 5000 lines.
Should colleges in the United States pay taxes?
47 Should colleges in the United States pay taxes?
1156207
Does mainland Chinese have bad hygiene?
39 Does mainland Chinese have bad hygiene?
1156208
How is it possible that I have blocked someone from my WhatsApp but still he is able to see my story on WhatsApp and my profile pic also?
137 How is it possible that I have blocked someone from my WhatsApp but still he is able to see my story on WhatsApp and my profile pic also?
1156209
Do you think internet moderators are, properly defined, basically someone who have no respect for someone's life and have a bloated sense of self-importance, and make it their task to aggressively, bullyingly make that clear at every opportunity?
246 Do you think internet moderators are, properly defined, basically someone who have no respect for someone's life and have a bloated sense of self-importance, and make it their task to aggressively, bullyingly mak

1017

In [ ]:
sent_length=max(l1)
sent_length

1017

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):

    review = re.sub('[^a-zA-Z]', ' ', messages['question_text'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[1]

'submit document differ document share site make document share document websit backlink websit new content upload'

In [ ]:
messages['question_text'][1]

'Can I submit same document in different document sharing sites? If I make 10 documents can I share same 10 documents in 4-5 websites for backlinks or each website new content I should upload?'

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[7383, 5427, 8701, 1241, 3125, 9386, 6931],
 [7582,
  6867,
  2398,
  6867,
  5514,
  2588,
  5691,
  6867,
  5514,
  6867,
  8998,
  4686,
  8998,
  4234,
  53,
  8570],
 [4022, 8286, 5366],
 [5155, 6402, 66],
 [2724, 7047, 931],
 [8190, 849, 4886, 7547, 797, 4796, 4022, 843, 3568],
 [8880, 6764, 4426],
 [4329, 6103, 8358],
 [469, 4306, 9078, 1522, 2448],
 [1430, 8202, 364],
 [5874, 1423, 6312, 4206, 9664, 4580, 6052, 1448, 880, 6052, 1448, 4980, 536],
 [3927, 1996, 1996, 5852, 4914],
 [4965, 4094, 7339, 842, 7538, 5995],
 [1176, 6190, 8580, 1122, 2305, 3033, 9775, 4340, 3033, 5248],
 [3979, 9301, 3496, 8260, 3512, 7803],
 [2333, 4288, 2984, 3182, 1057, 3979, 2588],
 [1869, 9908, 9678, 775, 4329, 3071, 7121, 351, 1282, 351, 7121],
 [2981, 9655, 6526],
 [4326, 4696, 2445, 8033, 7332, 6888],
 [9485,
  7099,
  3132,
  6110,
  2122,
  2811,
  8243,
  530,
  5188,
  4630,
  6736,
  2444,
  3132,
  6110,
  6736],
 [864, 6777],
 [6482, 4986, 9757, 9538, 600],
 [6980,
  1013,
  2044,
  6174,

In [ ]:
# sent_length=190
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3125 9386 6931]
 [   0    0    0 ... 4234   53 8570]
 [   0    0    0 ... 4022 8286 5366]
 ...
 [   0    0    0 ...  417 9655 9873]
 [   0    0    0 ... 7956 7894 7381]
 [   0    0    0 ... 8187 4841 7199]]


In [ ]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1017, 40)          400000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 456,501
Trainable params: 456,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),Y.shape

NameError: name 'embedded_docs' is not defined

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [ ]:
X_final

array([[   0,    0,    0, ..., 3125, 9386, 6931],
       [   0,    0,    0, ..., 4234,   53, 8570],
       [   0,    0,    0, ..., 4022, 8286, 5366],
       ...,
       [   0,    0,    0, ...,  417, 9655, 9873],
       [   0,    0,    0, ..., 7956, 7894, 7381],
       [   0,    0,    0, ..., 8187, 4841, 7199]], dtype=int32)

In [ ]:
b.shape,y_final.shape

NameError: name 'b' is not defined

In [ ]:
X_final=b = X_final[np.logical_not(np.isnan(X_final))]


NameError: name 'X_final' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

ValueError: Found input variables with inconsistent numbers of samples: [1157872, 1157871]

In [ ]:
X_train.shape,y_train.shape

In [ ]:
X_test.shape,y_test.shape

In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=3,batch_size=64)

In [ ]:
# scores = model.evaluate(X_test, y_test, verbose=0)
# print("Accuracy: %.2f%%" % (scores[1]*100))

In [ ]:
# y_pred1=model.predict_classes(X_test)
y_pred1= model.predict(X_test)
y_pred1=np.round(y_pred1)
y_pred1=y_pred1.astype('float')

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

In [ ]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

In [ ]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=1,batch_size=64)

In [ ]:
# y_pred2=model1.predict_classes(X_test)
y_pred2= model1.predict(X_test)
y_pred2=np.round(y_pred2)
y_pred2=y_pred2.astype('float')

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred2)